# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dejpdHRbIP6nKaJeIauk2TxEfMFZZXIQ
"""

!pip install streamlit

import streamlit as st
st.write('Hello world')